Repository dataforgoodfr/13_odis, pull requests merged in 2025-03, with the labels that each got.

#38 Documentation ELT et approche adoptée
  README.md
Labels: documentation

#33 added simple logger
  .gitignore
  bin/extract.py
  common/utils/logging_config.yml
  common/utils/logging_odis.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#40 37 el v02 modulariser choix sources
  .gitignore
  bin/extract.py
  common/utils/source_extractors.py
  datasources.yaml
  poetry.lock
  pyproject.toml
Labels: enhancement

#55 Prise en compte de throttling pour les API des extractor
  common/utils/source_extractors.py
  datasources.yaml
Labels: enhancement, frameworks

#53 Feat/add-bruno-collections
  .gitignore
  common/collections/France Travail - API offres/AUTH - generate access token.bru
  common/collections/France Travail - API offres/ROME - List Appellations.bru
  common/collections/France Travail - API offres/ROME - List Langues.bru
  common/collections/France Travail - API offres/bruno.json
  common/collections/France Travail - API offres/environments/France Travail.bru
  common/collections/INSEE - Melodi API/Get Dataset CSV.bru
  common/collections/INSEE - Melodi API/Get Dataset.bru
  common/collections/INSEE - Melodi API/Get Datastructure by ID.bru
  common/collections/INSEE - Melodi API/List Catalog Datasets descriptions.bru
  common/collections/INSEE - Melodi API/List Catalog IDs.bru
  common/collections/INSEE - Melodi API/bruno.json
  common/collections/INSEE - Melodi API/collection.bru
  common/collections/INSEE - Melodi API/environments/INSEE Melodi.bru
  common/collections/URSSAF open API/Catalog - List Datasets.bru
  common/collections/URSSAF open API/Catalog - List Export Formats.bru
  common/collections/URSSAF open API/Catalog - List Facets.bru
  common/collections/URSSAF open API/Dataset - List exports urls.bru
  common/collections/URSSAF open API/Dataset - get records (json).bru
  common/collections/URSSAF open API/bruno.json
  common/collections/URSSAF open API/collection.bru
  common/collections/URSSAF open API/environments/URSSAF env.bru
Labels: documentation, data exploration

#54 Modélisation objet de la configuration des data sources
  .gitignore
  EXTRACT.md
  common/config.py
  common/data_source_model.py
  common/tests/__init__.py
  common/tests/conftest.py
  common/tests/stubs/__init__.py
  common/tests/stubs/source_extractor_stub.py
  common/tests/test_config.py
  common/tests/test_data_source_model.py
  common/tests/test_source_extractors.py
  common/utils/logging_odis.py
  common/utils/source_extractors.py
  poetry.lock
  pyproject.toml
Labels: enhancement, frameworks

#60 Prep work : Extractors as paginated generators
  EXTRACT.md
  README.md
  bin/extract.py
  common/collections/INSEE - Melodi API/Get Dataset.bru
  common/data_source_model.py
  common/tests/test_data_source_model.py
  common/utils/file_handler.py
  common/utils/logging_config.yml
  common/utils/source_extractors.py
  datasources.yaml
  docs/configurations.md
  docs/extract.md
Labels: enhancement, frameworks

#61 55- Documentation dans les models.yml, dbt docs et readme de DBT
  DBT.md
  README.md
  dbt_odis/.gitignore
  dbt_odis/README.md
  dbt_odis/dbt_project.yml
  dbt_odis/models/bronze/_odis_bronze__models.yml
  dbt_odis/models/bronze/_odis_bronze__sources.yml
  dbt_odis/models/example/my_first_dbt_model.sql
  dbt_odis/models/example/my_second_dbt_model.sql
  dbt_odis/models/example/schema.yml
  dbt_odis/models/silver/_odis_silver__models.yml
  dbt_odis/models/silver/_odis_silver__sources.yml
Labels: documentation

#22 Logements - Melodi
  common/collections/INSEE - Melodi API - Logement/CATALOG.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - ALL.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - DATAS.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - NB PIECES.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - PIECES.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - RANGE.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - SIZE.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - TYPE DE CONSTRUCTION.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_LOGEMENT_PRINC - VACANT.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_POPULATION_PRINC - DATAS.bru
  common/collections/INSEE - Melodi API - Logement/DS_RP_POPULATION_PRINC - RANGE.bru
  common/collections/INSEE - Melodi API - Logement/bruno.json
  datasources.yaml
Labels: help wanted, data exploration

#67 Feat/education
  common/collections/Data Education Gouv API/bruno.json
  common/collections/Data Education Gouv API/moyenne d'eleves par classe par commune.bru
  datasources.yaml
Labels: data exploration

#66 Feat/services
  common/collections/Services/Agence de travail temporaire.bru
  common/collections/Services/Agence postale.bru
  common/collections/Services/Banque caisse d'epargne.bru
  common/collections/Services/Bureau de poste.bru
  common/collections/Services/Coiffure.bru
  common/collections/Services/Ecole de conduite.bru
  common/collections/Services/Implementations france services.bru
  common/collections/Services/Reseau de proximite pole emploi.bru
  common/collections/Services/Restaurant - restauration rapide.bru
  common/collections/Services/bruno.json
  datasources.yaml
Labels: data exploration

#78 Feat/line-by-line-jsonloader
  bin/odis.py
  common/collections/DiDo - Logement/Catalogue - Dataset Details.bru
  common/collections/DiDo - Logement/Catalogue - List Datasets.bru
  common/collections/DiDo - Logement/Datafiles - Get Datafile JSON.bru
  common/collections/DiDo - Logement/bruno.json
  common/collections/DiDo - Logement/environments/DiDo.bru
  common/collections/OpenDataSoft/ODS - Elus Communes.bru
  common/collections/OpenDataSoft/bruno.json
  common/data_source_model.py
  common/utils/data_loaders.py
  common/utils/database_client.py
  datasources.yaml
Labels: enhancement, frameworks

#75 Emploi - Ajout des statistiques demandeur emploi
  bin/odis.py
  common/utils/data_loaders.py
  datasources.yaml
Labels: data exploration

#79 Test/testing refacto
  bin/__init__.py
  bin/odis.py
  bin/tests/__init__.py
  bin/tests/conftest.py
  bin/tests/stubs/__init__.py
  bin/tests/stubs/handler.py
  bin/tests/test_odis_cli.py
  common/config.py
  common/data_source_model.py
  common/tests/stubs/data_handler.py
  common/tests/stubs/source_extractor_stub.py
  common/tests/test_abstract_extractor.py
  common/tests/test_config.py
  common/tests/test_data_source_model.py
  common/tests/test_extractory_factory.py
  common/tests/test_file_handler.py
  common/tests/test_source_extractors.py
  common/utils/__init__.py
  common/utils/data_loaders.py
  common/utils/factory/__init__.py
  common/utils/factory/extractor_factory.py
  common/utils/factory/loader_factory.py
  common/utils/file_handler.py
  common/utils/interfaces/__init__.py
  common/utils/interfaces/data_handler.py
  common/utils/interfaces/data_loader.py
  common/utils/interfaces/extractor.py
  common/utils/logging_odis.py
  common/utils/source_extractors.py
  data/.DS_Store
  poetry.lock
  pyproject.toml
Labels: enhancement

#94 Test/data loaders
  common/data_source_model.py
  common/tests/conftest.py
  common/tests/data/test_array_of_json.json
  common/tests/data/test_bad_data.json
  common/tests/data/test_data.csv
  common/tests/data/test_data.json
  common/tests/test_abstract_data_loader.py
  common/tests/test_csv_loader.py
  common/tests/test_data_source_model.py
  common/tests/test_json_loader.py
  common/utils/data_loaders.py
  common/utils/database_client.py
  common/utils/exceptions.py
  common/utils/factory/loader_factory.py
  common/utils/file_handler.py
  common/utils/interfaces/data_loader.py
  common/utils/interfaces/db_client.py
  poetry.lock
  pyproject.toml
Labels: CI
